version: '3.1'

services:

  drupal:
    build:
        context: .
        dockerfile: Dockerfile
    image: ardellio/drupal
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    volumes:
      - drupal-modules:/var/www/html/modules 
      - drupal-profiles:/var/www/html/profiles 
      - drupal-sites:/var/www/html/sites 
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres
    secrets:
      - psql_pass
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql_pass:
    file: ./psql_pass.txt
